# .github/workflows/terraform-dev
name: "Z-BASE Deploy UI: Run a deploy job for the UI"

on:
  workflow_call:
    inputs:
      build_branch:
        description: "Branch with smoke tests."
        required: true
        type: "string"
      environment:
        description: "Environment to run against"
        required: true
        type: string
      sandbox:
        description: "Sandbox to push code to"
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  react_build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'nhsconnect/national-document-repository'
          ref: ${{ inputs.build_branch }}
          fetch-depth: '0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: '/ndr/${{ inputs.sandbox }}/api_endpoint = DOC_STORE_API_ENDPOINT, 
            /ndr/${{ inputs.sandbox }}/container_port = CONTAINER_PORT'
          withDecryption: 'true' # defaults to true

      - name: Configure React environment vars
        env:
          ENDPOINT_DOC_STORE_API: ${{ env.DOC_STORE_API_ENDPOINT }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          OIDC_PROVIDER_ID: not provided yet
          BUILD_ENV: ${{ inputs.environment }}
          IMAGE_VERSION: 'ndr-${{ inputs.sandbox }}-app:${{ github.sha }}'
        run: |
          ./react-environment-config.sh

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ndr-${{ inputs.sandbox }}-app
          IMAGE_TAG: latest
          IMAGE_TAG_SHA: ${{ github.sha }}
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
        run: |
          docker build --build-arg="CONTAINER_PORT=$CONTAINER_PORT" -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA" >> $GITHUB_OUTPUT

      # Looks like the ECS does not check for image updates, as such we need to force a new task definition to run the new image
      # We will always use the "latest" image tag so we do not need to modify the task-definition
      - name: Download task definition
        id: download-task
        run: |
          aws ecs describe-task-definition --task-definition ${{ inputs.sandbox }}-task-app-cluster --query taskDefinition > task-definition.json
          echo "::set-output name=revision::$(cat task-definition.json | jq .revision)"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./app/task-definition.json
          container-name: ${{ inputs.sandbox }}-container-app-cluster
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ./app/task-definition.json
          service: ${{ inputs.sandbox }}-ecs-cluster-service
          cluster: ${{ inputs.sandbox }}-app-cluster
          wait-for-service-stability: true

      - name: De-register previous revision
        run: |
          aws ecs deregister-task-definition \
            --task-definition ${{ inputs.sandbox }}-task-app-cluster:${{ steps.download-task.outputs.revision }}
