# .github/workflows/terraform-dev
name: 'Z-BASE Cypress Test: Run a cypress test job against all browsers'

on:
  workflow_call:
    inputs:
      build_branch:
        description: 'Branch with smoke tests.'
        required: true
        type: 'string'
      environment:
        description: "Which Environment settings to use."
        required: true
        type: "string"
        default: "development"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
    cypress_test_chrome:
      uses: ./.github/workflows/base-cypress-test.yml
      with:
        build_branch: main
        environment: ${{ github.event.inputs.environment}}
        cypress_broswer: 'chrome'
    cypress_test_edge:
      uses: ./.github/workflows/base-cypress-test.yml
      with:
        build_branch: main
        environment: ${{ github.event.inputs.environment}}
        cypress_broswer: 'edge'
    cypress_test_firefox:
      uses: ./.github/workflows/base-cypress-test.yml
      with:
        build_branch: main
        environment: ${{ github.event.inputs.environment}}
        cypress_broswer: 'firefox'
