# .github/workflows/terraform-dev
name: 'Z-BASE Cypress Test Base: Run a cypress test job against a specific browser'

on:
  workflow_call:
    inputs:
      build_branch:
        description: 'Branch with smoke tests.'
        required: true
        type: 'string'
      base_url:
        description: 'application url to run cypress againsr'
        required: true
        type: 'string'
      cypress_broswer:
        description: 'what browser to run against'
        required: true
        type: 'string'

    secrets:
      AWS_ASSUME_ROLE:
        required: true
      CYPRESS_USERNAME:
        required: true
      CYPRESS_PASSWORD:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cypress-run-job:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: ${{ github.event.inputs.buildBranch }}

          - name: Download the build folder
            uses: actions/download-artifact@v3
            with:
              name: build
              path: ./app/build

          # Npm run will run the app locally, we want to test the built application with env vars using serve
          - name: Install serve globally
            run: npm install -g serve

          - name: Cypress install
            run: |
              npm install --legacy-peer-deps
            working-directory: ./app

          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
              install: false
              start: serve -s build
              browser: ${{ github.event.inputs.cypress_browser}}
              working-directory: ./app
            env:
              CYPRESS_BASE_URL: ${{ github.event.inputs.base_url }}
              CYPRESS_grepTags: 'regression'
