name: "Z-BASE Cypress Test: Run a cypress test job against all browsers"

on:
  workflow_call:
    inputs:
      build_branch:
        description: "Branch to run against"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cypress_test_chrome:
    uses: ./.github/workflows/base-cypress-test.yml
    with:
      build_branch: ${{ github.event.inputs.build_branch }}
      cypress_broswer: "chrome"
  cypress_test_edge:
    uses: ./.github/workflows/base-cypress-test.yml
    with:
      build_branch: ${{ github.event.inputs.build_branch }}
      cypress_broswer: "edge"
  cypress_test_firefox:
    uses: ./.github/workflows/base-cypress-test.yml
    with:
      build_branch: ${{ github.event.inputs.build_branch }}
      cypress_broswer: "firefox"
