name: "PRE PROD Full- Deploy and Version Main to Pre-Prod"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push?"
        required: true
        type: "string"
        default: "main"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      environment:
        description: "Which Environment settings to use."
        required: true
        type: "string" 
        default: "development"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:

  view_action_parameters:
    name: View input params
    runs-on: ubuntu-latest
    steps: 
    
      - name: Display client passed variables
        run: |
          echo Build Branch: ${{ inputs.build_branch }}
          echo Sandbox: ${{ inputs.sandbox }}
          echo Environment: ${{ inputs.environment }}
          echo Cypress Base Url: ${{ vars.CYPRESS_BASE_URL }}

  lambda_test_job:
    name: Run Lambda Unit Tests
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}

  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-jest-test.yml
    with:
      build_branch: ${{ inputs.build_branch }}

  cypress_build_job:
    name: Build UI version for E2E Tests
    uses: ./.github/workflows/base-cypress-build.yml
    with:
      build_branch: ${{ inputs.build_branch }}
  
  cypress_test_job:
    name: Run Cypress E2E Tests
    needs: [cypress_build_job]
    uses: ./.github/workflows/base-cypress-test-all-env.yml
    with:
      cypress_base_url: ${{ vars.CYPRESS_BASE_URL }}
      build_branch: ${{ inputs.build_branch }}
      
  tag_and_release:
    needs: ["lambda_test_job", "react_testing_job", "cypress_test_job"]
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.versioning.outputs.tag}}
      new_tag: ${{steps.versioning.outputs.new_tag}}
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.build_branch }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: versioning
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
    
    - name: View outputs
      run: |
        echo Current tag: ${{steps.versioning.outputs.tag}} 
        echo New tag: ${{steps.versioning.outputs.new_tag}}

  deploy_all_lambdas:
    name: Deploy all Lambdas
    needs: ["tag_and_release"]
    uses: ./.github/workflows/lambdas-deploy-feature-to-sandbox.yml
    with:
      build_branch: ${{ needs.tag_and_release.outputs.tag }}
      sandbox: ${{ inputs.sandbox }}
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  
  deploy_ui:
    name: Deploy UI
    needs: ["tag_and_release"]
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ needs.tag_and_release.outputs.tag }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ECR_REPO_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}

  

        