name: "SANDBOX Full- Deploy feature branch to sandbox"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push?"

        required: true
        type: "string"
        default: "main"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      environment:
        description: "Which Environment settings to use."
        required: true
        type: "string"
        default: "development"
      bulk_upload:
        description: "Do you want to run a Bulk Upload on this sandbox?"
        required: true
        type: boolean
        default: false

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  view_action_parameters:
    name: View input params
    runs-on: ubuntu-latest
    steps:
      - name: Display client passed variables
        run: |
          echo Build Branch: ${{ inputs.build_branch }}
          echo Sandbox: ${{ inputs.sandbox }}
          echo Environment: ${{ inputs.environment }}
          echo Cypress Base Url: ${{ vars.CYPRESS_BASE_URL }}

  lambda_test_job:
    name: Run Lambda Unit Tests
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}

  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-jest-test.yml
    with:
      build_branch: ${{ inputs.build_branch }}

  cypress_build_job:
    name: Build UI version for E2E Tests
    uses: ./.github/workflows/base-cypress-build.yml
    with:
      build_branch: ${{ inputs.build_branch }}

  cypress_test_job:
    name: Run Cypress E2E Tests
    needs: [cypress_build_job]
    uses: ./.github/workflows/base-cypress-test-all-env.yml
    with:
      cypress_base_url: ${{ vars.CYPRESS_BASE_URL }}
      build_branch: ${{ inputs.build_branch }}

  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      sandbox: ${{ inputs.sandbox }}
      environment: ${{ inputs.environment }}
      python_version: "3.11"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all_lambdas:
    name: Deploy all Lambdas
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["publish_all_lambda_layers"]
    with:
      build_branch: ${{ inputs.build_branch }}
      sandbox: ${{ inputs.sandbox }}
      environment: ${{ inputs.environment }}
      python_version: "3.11"
      is_sandbox: true
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  bulk_upload:
    name: "Run Bulk Upload"
    if: ${{ inputs.bulk_upload }}
    uses: "./.github/workflows/base-run-bulk-upload.yml"
    with:
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
      combi-settings: "combi300"
      file-count: "1"
