name: "PROD Full - Deploy tagged version to Prod"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "What tagged version do you want to push to prod?"
        required: true
        type: "string"

permissions:
  actions: read   # Required for anchore/sbom-action
  contents: write # Required for anchore/sbom-action
  pull-requests: write
  id-token: write # This is required for requesting the JWT

env:
  PYTHON_VERSION: "3.11"
  ENVIRONMENT: prod
  SANDBOX: prod
  BUILD_BRANCH: ${{ inputs.tag_version }}

jobs:
  view_action_parameters:
    name: View input params
    runs-on: ubuntu-latest
    steps: 
      - name: Display client passed variables
        run: |
          echo Build Branch: ${{ inputs.tag_version }}
          echo Sandbox: prod
          echo Environment: prod

  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    with:
      build_branch: ${{ inputs.tag_version }}
      sandbox: prod
      environment: prod
      python_version: "3.11"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all_lambdas:
    name: Deploy all Lambdas
    needs: ["publish_all_lambda_layers"]
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    with:
      build_branch: ${{ inputs.tag_version }}
      sandbox: prod
      environment: prod
      python_version: "3.11"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  
  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ inputs.tag_version }}
      environment: prod
      sandbox: prod
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_data_collection:
    name: Deploy ODS Data Collection
    uses: ./.github/workflows/base-data-collection.yml
    with:
      build_branch: ${{ inputs.tag_version }}
      environment: prod
      sandbox: prod
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
