name: "TEST Lambdas - Deploy Feature Branch to Test"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push to test?"
        required: true
        type: "string"
      mock_login_enabled:
        description: "Do you want to deploy with mock login enabled?"
        required: true
        type: boolean
        default: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_tests:
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}

  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    needs: ["run_tests"]
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    with:
      environment: test
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}
      sandbox: ndr-test
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all_lambdas:
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests", "publish_all_lambda_layers"]
    with:
      environment: test
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}
      sandbox: ndr-test
      mock_login_enabled: ${{ inputs.mock_login_enabled }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  

        