name: 'CI Lambdas - CI Feature to Main'

on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  check_packages:
    uses: ./.github/workflows/base-lambdas-check-packages.yml
    with:
      environment: development
      python_version: 3.11
      build_branch: ${{github.event.pull_request.head.ref}}

  run_tests:
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: 3.11
      build_branch: ${{github.event.pull_request.head.ref}}

  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    needs: [ "run_tests" ]
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    if: |
      (github.ref == 'refs/heads/main')
    with:
      environment: development
      python_version: '3.11'
      build_branch: ${{github.event.pull_request.head.ref}}
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all_lambdas:
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests", "publish_all_lambda_layers"]
    if: |
      (github.ref == 'refs/heads/main')
    with:
      environment: development
      python_version: '3.11'
      build_branch: ${{github.event.pull_request.head.ref}}
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
