name: "PROD Lambdas - Deploy tagged version to Prod"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Which tagged version do you want to push to prod?"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  PYTHON_VERSION: "3.11"
  ENVIRONMENT: prod
  SANDBOX: prod
  BUILD_BRANCH: ${{ inputs.tag_version }}

jobs:
  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    with:
      environment: prod
      python_version: "3.11"
      build_branch: ${{ inputs.tag_version }}
      sandbox: prod
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all:
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["publish_all_lambda_layers"]
    with:
      environment: prod
      python_version: "3.11"
      build_branch: ${{ inputs.tag_version }}
      sandbox: prod
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
