name: "PERF Lambdas - Deploy Feature Branch to Perf"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push to test?"
        required: true
        type: "string"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_tests:
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}

  deploy_all:
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests"]
    with:
      environment: perf
      python_version: "3.11"
      build_branch: ${{ inputs.build_branch }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  

        