# .github/workflows/terraform-dev
name: "Merge to main: E2e Tests Backend"

on:
  workflow_run:
    workflows:
      [
        'CI Lambdas - CI Feature to Main'
      ]
    types:
      - completed

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
   services-e2etest:
    uses: ./.github/workflows/base-e2e-backendtest.yml
    with:
      build_branch: main
      environment: development
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
