# .github/workflows/terraform-dev
name: "Cypress Smoketest CI to Main: Smoketest shared actions checking CI deployments"

on:
  workflow_run:
    workflows:
      [
        'CI UI - Development CI Feature Branch to Main',
        'CI Lambdas - CI Feature to Main'
      ]
    types:
      - completed

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  smoketest:
    uses: ./.github/workflows/base-cypress-smoketest.yml
    with:
      build_branch: main
      environment: development
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
