# .github/workflows/terraform-dev
name: "Merge to main: E2e Tests UI and Backend"

on:
  workflow_run:
    workflows:
      [
        "CI UI - Development CI Feature Branch to Main",
        "CI Lambdas - CI Feature to Main",
      ]
    types:
      - completed

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  ui-e2etest:
    uses: ./.github/workflows/base-cypress-e2e.yml
    with:
      build_branch: main
      environment: development
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
  services-e2etest:
    uses: ./.github/workflows/base-e2e-backendtest.yml
    with:
      build_branch: main
      environment: development
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
