name: "Lambdas - Deploy Feature Branch to Sandbox"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push to test?"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  PYTHON_VERSION: "3.11"
  ENVIRONMENT: test
  SANDBOX: ndr-test
  BUILD_BRANCH: ${{ inputs.build_branch}}

jobs:
  run_tests:
    uses: ./.github/workflows/new_base-lambdas-reusable-test.yml
    with:
      environment: ${{ env.ENVIRONMENT }}
      python-version: ${{ env.PYTHON_VERSION }}
      build-branch: ${{ env.BUILD_BRANCH}}

  deploy_all:
    uses: ./.github/workflows/new_base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests"]
    with:
      environment: ${{ env.ENVIRONMENT }}
      python-version: ${{ env.PYTHON_VERSION }}
      build-branch: ${{ env.BUILD_BRANCH}}
      sandbox: ${{ env.SANDBOX }}

  

        