name: "BASE: Lambda test runner"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      python_version:
        required: true
        type: string
      build_branch:
        required: true
        type: string
        default: main

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  PYTHON_VERSION: ${{ inputs.python_version }}
  ENVIRONMENT: ${{ inputs.environment }}
  BUILD_BRANCH: ${{ inputs.build_branch }}
  SANDBOX: ${{ inputs.sandbox }}

jobs:
  view_action_parameters:
    runs-on: ubuntu-latest
    steps: 
    
      - name: Display client passed variables
        run: |
          echo Python Version: $PYTHON_VERSION
          echo Build Branch: $BUILD_BRANCH
          echo Environment: $ENVIRONMENT
          echo Sandbox: $SANDBOX

  python_unit_tests:
    runs-on: ubuntu-latest
    environment: $ENVIRONMENT

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: $BUILD_BRANCH

      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v4
        with:
          python_version: $PYTHON_VERSION

      - name: Make virtual environment
        run: | 
          make env
      
      - name: Start virtual environment
        run: |
          source ./lambdas/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Format Code and ruff check
        run: |
          make format

      - name: Test with pytest
        run: |
          make test-unit