name: " CI Lambdas - CI Feature to Main"

on:
  push:
    branches:
      - main
    paths:
      - "lambdas/**"
  pull_request:
    branches:
      - main
    paths:
      - "lambdas/**"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  check_packages:
    uses: ./.github/workflows/lambdas-check-packages.yml
    with:
      environment: development
      python_version: 3.11
      build_branch: ${{github.event.pull_request.head.ref}}

  run_tests:
    uses: ./.github/workflows/new_base-lambdas-reusable-test.yml
    with:
      python_version: 3.11
      build_branch: ${{github.event.pull_request.head.ref}}

  deploy_all_lambdas:
    uses: ./.github/workflows/new_base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests"]
    if: |
      (github.ref == 'refs/heads/main') 
    with:
      environment: development
      python_version: "3.11"
      build_branch: ${{github.event.pull_request.head.ref}}
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  
  # smoketest:
  #   uses: ./.github/workflows/ui-smoketest-base.yml
  #   needs: ["deploy_all_lambdas"]
  #   if: |
  #     (github.ref == 'refs/heads/main') 
  #   with:
  #     build_branch: ${{github.event.pull_request.head.ref}}
  #     environment: development
  #     sandbox: ndr-dev
  #     aws_region: ${{ vars.AWS_REGION }}
  #   secrets:
  #     AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  #     CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
  #     CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  

        