name: "Lambdas - Deploy and Version Main to Pre-Prod"

on:
  push:
    branches:
      - main
    paths:
      - "lambdas/**"
  pull_request:
    branches:
      - main
    paths:
      - "lambdas/**"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  PYTHON_VERSION: "3.11"
  ENVIRONMENT: development
  BUILD_BRANCH: main
  SANDBOX: ndr-dev

jobs:
  run_tests:
    uses: ./.github/workflows/new_base-lambdas-reusable-test.yml
    with:
      environment: ${{ env.ENVIRONMENT }}
      python-version: ${{ env.PYTHON_VERSION }}
      build-branch: ${{ env.BUILD_BRANCH }}

  deploy_all_lambdas:
    uses: ./.github/workflows/new_base-lambdas-reusable-deploy-all.yml
    needs: ["run_tests"]
    if: |
      (github.ref == 'refs/heads/main') 
    with:
      environment: ${{ env.ENVIRONMENT }}
      python-version: ${{ env.PYTHON_VERSION }}
      build-branch: ${{ env.BUILD_BRANCH }}
      sandbox: ${{ env.SANDBOX }}

  

        