name: Run Bulk Upload - Dev

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      combi_settings:
        description: "Use 300 or 8000 patients"
        required: true
        type: choice
        options:
          - "combi300"
          - "combi8000"
      file_count:
        description: "How many files per patient"
        required: true
        type: "string"
        default: "1"

jobs:
  bulk_upload:
    uses: ./.github/workflows/base-run-bulk-upload.yml
    with:
      environment: development
      sandbox: "${{ inputs.sandbox }}"
      combi_settings: "${{ inputs.combi_settings }}"
      file_count: "${{ inputs.file_count }}"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
