name: 'PROD UI - Deploy tagged version to Prod'

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Which tagged version do you want to push to prod?'
        required: true
        type: 'string'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ inputs.tag_version }}
      environment: prod
      sandbox: prod
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}