# .github/workflows/terraform-dev
name: "CI UI - Development CI Feature Branch to Main"

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "app/**"
      - "Makefile"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"
      - "app/**"
      - "Makefile"
  workflow_call:
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  actions: read   # Required for anchore/sbom-action
  contents: write # Required for anchore/sbom-action
  pull-requests: write
  id-token: write # This is required for requesting the JWT

jobs:
  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-vitest-test.yml
    with:
      build_branch: ${{github.event.pull_request.head.ref}}

  cypress_build_job:
    name: Build UI version for E2E Tests
    uses: ./.github/workflows/base-cypress-build.yml
    with:
      build_branch: ${{github.event.pull_request.head.ref}}

  cypress_test_job:
    name: Run Cypress E2E Tests
    needs: [cypress_build_job]
    uses: ./.github/workflows/base-cypress-test-all-env.yml
    with:
      cypress_base_url: ${{ vars.CYPRESS_BASE_URL }}
      build_branch: ${{github.event.pull_request.head.ref}}

  deploy_ui:
    name: Deploy UI
    if: github.ref == 'refs/heads/main'
    needs: ["react_testing_job", "cypress_test_job"]
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{github.event.pull_request.head.ref}}
      environment: development
      sandbox: ndr-dev
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
