# .github/workflows/terraform-dev
name: 'TEST UI - Deploy Main to Test'

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: 'Feature branch to push to test?'
        required: true
        type: 'string'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-jest-test.yml
    with:
      build_branch: ${{ inputs.build_branch }}

  cypress_build_job:
    name: Build UI version for E2E Tests
    uses: ./.github/workflows/base-cypress-build.yml
    with:
      build_branch: ${{ inputs.build_branch }}
  
  cypress_test_job:
    name: Run Cypress E2E Tests
    needs: [cypress_build_job]
    uses: ./.github/workflows/base-cypress-test-all-env.yml
    with:
      cypress_base_url: ${{ vars.CYPRESS_BASE_URL }}
      build_branch: ${{ inputs.build_branch }}
        
  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: test
      sandbox: ndr-test
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ECR_REPO_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}
