name: 'UI - Deploy Main to Pre-Prod'

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  tag_and_release:
    runs-on: ubuntu-latest
    environment: pre-prod
    outputs:
      new_version: ${{steps.versioning.outputs.new_tag}}
    defaults:
      run:
        working-directory: ./app

    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: '0'

    - name: Bump version and push tag
      id: versioning
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false

  react_testing_job:
    runs-on: ubuntu-latest
    environment: pre-prod
    defaults:
      run:
        working-directory: ./app
    needs: ['tag_and_release']

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: needs.tag_and_release.outputs.new_tag

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # needs confirmation on sass install location
    - run: npm i sass 
    # - run: npm run build --if-present
    - run: npm test
  
  react_build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    environment: pre-prod
    defaults:
      run:
        working-directory: ./app
    needs: ['react_testing_job', 'tag_and_release']

    steps:

    - uses: actions/checkout@v2
      with:
        ref: needs.tag_and_release.outputs.new_tag
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-skip-session-tagging: true
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        IMAGE_TAG: ${{ github.event.inputs.tagVersion}}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    