name: 'SANDBOX UI - Deploy Feature Branch to Sandbox'

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Feature branch to push."
        required: true
        type: "string"
        default: "main"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      environment:
        description: "Which Environment settings to use."
        required: true
        type: "string"
        default: "development"
  workflow_call:
    inputs:
      build_branch:
        description: "Feature branch to push."
        required: true
        type: "string"
        default: "main"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      environment:
        description: "Which Environment settings to use."
        required: true
        type: "string"
        default: "development"
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:

  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-jest-test.yml
    with:
      build_branch: ${{ inputs.build_branch }}

  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}