# .github/workflows/terraform-dev
name: 'UI - Deploy Feature Branch to Sandbox'

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: "Feature branch to push to test?"
        required: true
        type: "string"
      sandboxWorkspace:
        description: "Which Sandbox to push to."
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  react_testing_job:
    runs-on: ubuntu-latest
    environment: development
    env:
      DOC_STORE_API_ENDPOINT: "Not configured"
      
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.buildBranch}}


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  react_build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.buildBranch}}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-skip-session-tagging: true
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - uses: dkershner6/aws-ssm-getparameters-action@v1
      with:
          parameterPairs: "ndr/${{ github.event.inputs.sandboxWorkspace}}/api_endpoint = DOC_STORE_API_ENDPOINT"
          withDecryption: "true" # defaults to true

    - name: Configure React environment vars
      env:
        ENDPOINT_DOC_STORE_API: ${{env.DOC_STORE_API_ENDPOINT}}
        AWS_REGION: ${{ vars.AWS_REGION }}
        OIDC_PROVIDER_ID: not provided yet
        BUILD_ENV: development
        IMAGE_VERSION: "ndr-${{ github.event.inputs.sandboxWorkspace}}-app:${{ github.sha }}"
      run: |
        ./react-environment-config.sh
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ndr-${{ github.event.inputs.sandboxWorkspace}}-app
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  