# .github/workflows/terraform-dev
name: 'UI - Deploy tagged version to Prod'

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        description: "What tagged verison do you want to push to prod?"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  react_testing_job:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tagVersion}}
        fetch-depth: '0'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # needs confirmation on sass install location
    - run: npm i sass 
    # - run: npm run build --if-present
    - run: npm test
  
  react_build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./app
    needs: react_testing_job

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tagVersion}}
        fetch-depth: '0'
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-skip-session-tagging: true
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        IMAGE_TAG: prod-${{ github.event.inputs.tagVersion}}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    