# .github/workflows/terraform-dev
name: 'SANDBOX - Smoke Test'

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: 'Branch with smoke tests.'
        required: true
        type: 'string'
        default: 'main'
      sandbox:
        description: 'Sandbox to run the smoke tests on.'
        required: true
        type: 'string'
        default: 'ndr'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'nhsconnect/national-document-repository'
          ref: ${{ github.event.inputs.build_branch}}

      - name: Cypress install
        run: |
          npm install --legacy-peer-deps
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          browser: chrome
          working-directory: ./app
        env:
          CYPRESS_BASE_URL: 'https://${{ github.event.inputs.sandbox }}.access-request-fulfilment.patient-deductions.nhs.uk'
          CYPRESS_grepTags: 'smoke'
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'nhsconnect/national-document-repository'
          ref: ${{ github.event.inputs.build_branch}}

      - name: Cypress install
        run: |
          npm install --legacy-peer-deps
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          browser: firefox
          working-directory: ./app
        env:
          CYPRESS_BASE_URL: 'https://${{ github.event.inputs.sandbox }}.access-request-fulfilment.patient-deductions.nhs.uk'
          CYPRESS_grepTags: 'smoke'
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'nhsconnect/national-document-repository'
          ref: ${{ github.event.inputs.build_branch}}

      - name: Cypress install
        run: |
          npm install --legacy-peer-deps
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          browser: edge
          working-directory: ./app
        env:
          CYPRESS_BASE_URL: 'https://${{ github.event.inputs.sandbox }}.access-request-fulfilment.patient-deductions.nhs.uk'
          CYPRESS_grepTags: 'smoke'
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
