# .github/workflows/terraform-dev
name: 'SANDBOX - Smoke Test'

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: 'Branch with smoke tests.'
        required: true
        type: 'string'
        default: 'main'
      environment:
        description: 'Which Environment type are we using'
        required: true
        type: 'string'
        default: 'development'
      sandbox:
        description: 'Sandbox to run the smoke tests on.'
        required: true
        type: 'string'
        default: 'ndr'
      aws_region:
        description: 'What AWS Region to run on'
        required: true
        type: 'string'
        default: 'eu-west-2'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
