name: Updated Run Bulk Upload - Test

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      combi_settings:
        description: "How many patients to create (default = 1)"
        required: true
        type: "string"
        default: "1"
      file_count:
        description: "How many files per patient"
        required: true
        type: "string"
        default: "1"

jobs:
  bulk_upload:
    uses: ./.github/workflows/updated-base-run-bulk-upload.yml
    with:
      environment: test
      sandbox: "ndrd"
      combi_settings: "${{ inputs.combi_settings }}"
      file_count: "${{ inputs.file_count }}"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
